// FAKE DATA
export const games = [
  {
    id: 1,
    title: "Legend of Zelda: Tears of the Kingdom",
    url: "https://images.nintendolife.com/3c28307f2fe0a/legend-of-zelda-tears-of-the-kingdom-cover.cover_300x.jpg",
    originalPrice: 49.99,
    salePrice: 24.99,
    rating: 5,
  },
  {
    id: 2,
    title: "Super Mario Bros Wonder",
    url: "https://images.nintendolife.com/aaa017bb4e5cc/super-mario-bros-wonder-cover.cover_300x.jpg",
    originalPrice: 49.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 3,
    title: "Pokemon Legends Arceus",
    url: "https://images.nintendolife.com/2889c0391401b/pokemon-legends-arceus-cover.cover_300x.jpg",
    originalPrice: 49.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Kirby and the Forgotten Land",
    url: "https://images.nintendolife.com/1ddb829d9a730/kirby-and-the-forgotten-land-cover.cover_300x.jpg",
    originalPrice: 39.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Super Mario Odyssey",
    url: "https://images.nintendolife.com/79d7d24eda071/super-mario-odyssey-cover.cover_300x.jpg",
    originalPrice: 29.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Persona 5 Royal",
    url: "https://images.nintendolife.com/a432b578fa21a/persona-5-royal-cover.cover_300x.jpg",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 5,
  },
  {
    id: 7,
    title: "Splatoon 3",
    url: "https://images.nintendolife.com/980331d444e98/splatoon-3-cover.cover_300x.jpg",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 4,
  },
  {
    id: 8,
    title: "Pokemon Let's Go Pikachu",
    url: "https://images.nintendolife.com/a74f6edfbe9e9/pokemon-lets-go-pikachu-and-lets-go-eevee-cover.cover_300x.jpg",
    originalPrice: 39.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Animal Crossing: New Horizons",
    url: "https://images.nintendolife.com/bf43ef284f030/animal-crossing-new-horizons-cover.cover_300x.jpg",
    originalPrice: 34.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Donkey Kong Country: Tropical Freeze",
    url: "https://images.nintendolife.com/68b153f4aa78f/donkey-kong-country-tropical-freeze-cover.cover_300x.jpg",
    originalPrice: 19.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Super Smash Bros. Ultimate",
    url: "https://images.nintendolife.com/73b5ee31cad64/super-smash-bros-ultimate-cover.cover_300x.jpg",
    originalPrice: 29.99,
    salePrice: 19.99,
    rating: 5,
  },
  {
    id: 12,
    title: "Metroid Dread",
    url: "https://images.nintendolife.com/7c1760474c995/metroid-dread-cover.cover_300x.jpg",
    originalPrice: 39.99,
    salePrice: 10.99,
    rating: 4.5,
  },
];